- hosts: imdown
  tasks:
    - name: Stop imdown
      service:
        name: imdown
        state: stopped
      become: yes

    - name: Deploy Application Files
      synchronize:
        src: ../../backend/
        dest: /home/ubuntu/imdown/backend/
        delete: yes

    - name: Update Requirements
      pip:
        requirements: /home/ubuntu/imdown/backend/requirements.txt

    - name: Start imdown
      service:
        name: imdown
        state: started
      become: yes
