- hosts: imdown
  tasks:
    - name: Stop imdown
      service:
        name: imdown
        state: stopped
      become: yes
    - name: Deploy Application Files
      synchronize:
        src: ../../backend/
        dest: /home/ubuntu/imdown/backend/
        delete: yes
    - name: Download FireBase Credentials
      aws_s3:
        bucket: imdown-credentials
        object: /firebase/imdown_firebase_cert.json
        dest: /home/ubuntu/imdown/backend/imdown_firebase_cert.json
        mode: get 
    - name: Delete .env file
      file:
        path: /home/ubuntu/imdown/backend/.env
        state: absent
    - name: Update Requirements
      pip:
        requirements: /home/ubuntu/imdown/backend/requirements.txt

    - block:
      - name: Start imdown
        service:
          name: imdown
          state: started
        become: yes
      rescue:
        - command: journalctl --unit=imdown.service -n 100 --no-pager
          register: status
          ignore_errors: yes
        - debug:
            var: status.stdout_lines
        - fail:
            msg: rrrr u broke th e server!!1!
