branch-defaults:
  default:
    environment: imdown
environment-defaults:
  imdown:
    branch: null
    repository: null
global:
  application_name: imdown
  default_ec2_keyname: imdown
  default_platform: arn:aws:elasticbeanstalk:us-west-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.5
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
