"""add squad code column

Revision ID: 29a95de4aea6
Revises: bfc9bdad220c
Create Date: 2020-07-29 20:14:38.968033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a95de4aea6'
down_revision = 'bfc9bdad220c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squad', sa.Column('code', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_squad_code'), 'squad', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_squad_code'), table_name='squad')
    op.drop_column('squad', 'code')
    # ### end Alembic commands ###
