"""add device token column to user

Revision ID: 32b24541db10
Revises: c62f8f0dfe63
Create Date: 2020-08-12 22:44:52.748997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b24541db10'
down_revision = 'c62f8f0dfe63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('device_token',
                                    sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'device_token')
    # ### end Alembic commands ###
