"""Add image for squad

Revision ID: 37cffe7a9fba
Revises: 5ea8f3a52849
Create Date: 2020-09-12 17:54:28.805435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37cffe7a9fba'
down_revision = '5ea8f3a52849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squad', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('squad', 'image')
    # ### end Alembic commands ###
