"""Add google refresh token and google access token to User model

Revision ID: 4072bc54db71
Revises: 80d0832d0caa
Create Date: 2020-08-01 18:14:30.846730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4072bc54db71'
down_revision = '80d0832d0caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_access_token',
                                    sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('google_refresh_token',
                                    sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'google_refresh_token')
    op.drop_column('user', 'google_access_token')
    # ### end Alembic commands ###
