"""leftover event image migration

Revision ID: 5ea8f3a52849
Revises: aabad5c84309
Create Date: 2020-09-10 21:24:45.602032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ea8f3a52849'
down_revision = 'aabad5c84309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'image_url',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'image_url',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
