"""make auth hash non nullable

Revision ID: 5f6d28756551
Revises: aaaace0bf2f5
Create Date: 2020-02-08 23:38:44.741708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f6d28756551'
down_revision = 'aaaace0bf2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'auth_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'auth_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
