"""Make user id in event response a FK

Revision ID: 6fad00d124d6
Revises: bd3858beccdd
Create Date: 2020-07-30 22:40:32.350171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fad00d124d6'
down_revision = 'bd3858beccdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_response_user_id', table_name='event_response')
    op.create_foreign_key('event_response_ibfk_1', 'event_response', 'user', ['user_id'], ['id'])
    op.alter_column('squad', 'squad_emoji',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('squad', 'squad_emoji',
               existing_type=sa.String(length=64),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               existing_nullable=True)
    op.drop_constraint('event_response_ibfk_1', 'event_response', type_='foreignkey')
    op.create_index('ix_event_response_user_id', 'event_response', ['user_id'], unique=False)
    # ### end Alembic commands ###
