"""Add image to squad

Revision ID: 77e4ebb2a766
Revises: b6e81caa582f
Create Date: 2020-09-12 23:14:14.114672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77e4ebb2a766'
down_revision = 'b6e81caa582f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squad', sa.Column('image', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('squad', 'image')
    # ### end Alembic commands ###
