"""Add down_threshold to event

Revision ID: 80d0832d0caa
Revises: 6b76b84f79b0
Create Date: 2020-08-04 22:19:49.622679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80d0832d0caa'
down_revision = '6b76b84f79b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('down_threshold', sa.Integer(), nullable=True))
    op.alter_column('squad', 'squad_emoji',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('squad', 'squad_emoji',
               existing_type=sa.String(length=64),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               existing_nullable=True)
    op.drop_column('event', 'down_threshold')
    # ### end Alembic commands ###
