"""Adding admin_id column to Squad table.

Revision ID: a2702db82e82
Revises: f5d4fa1ae369
Create Date: 2020-08-09 22:48:26.157767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2702db82e82'
down_revision = 'f5d4fa1ae369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squad', sa.Column('admin_id', sa.Integer, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('squad', 'admin_id')
    # ### end Alembic commands ###
