"""change start time and end time ms

Revision ID: aaaace0bf2f5
Revises: 1169158460b5
Create Date: 2020-02-08 20:17:38.502967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaaace0bf2f5'
down_revision = '1169158460b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_response_event_id', table_name='event_response')
    op.create_index(op.f('ix_event_response_event_id'), 'event_response', ['event_id'], unique=False)
    op.drop_index('ix_event_response_user_id', table_name='event_response')
    op.create_index(op.f('ix_event_response_user_id'), 'event_response', ['user_id'], unique=False)
    op.drop_index('response', table_name='event_response')
    op.create_unique_constraint(None, 'group', ['invite_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='unique')
    op.create_index('response', 'event_response', ['response'], unique=True)
    op.drop_index(op.f('ix_event_response_user_id'), table_name='event_response')
    op.create_index('ix_event_response_user_id', 'event_response', ['user_id'], unique=True)
    op.drop_index(op.f('ix_event_response_event_id'), table_name='event_response')
    op.create_index('ix_event_response_event_id', 'event_response', ['event_id'], unique=True)
    # ### end Alembic commands ###
