"""leftover migrations for events & admin id

Revision ID: aabad5c84309
Revises: ff6fa6db6348
Create Date: 2020-08-31 18:39:30.470812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aabad5c84309'
down_revision = 'ff6fa6db6348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'description',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('event', 'image_url',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_nullable=True)
    op.alter_column('squad', 'admin_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('squad', 'admin_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('event', 'image_url',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('event', 'description',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
