"""change code col type to string

Revision ID: aec812048cfe
Revises: 29a95de4aea6
Create Date: 2020-07-29 22:06:11.503034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aec812048cfe'
down_revision = '29a95de4aea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('squad', 'code',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('squad', 'code',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
