"""add event times table

Revision ID: b6e81caa582f
Revises: c3b2faf138c0
Create Date: 2020-09-12 23:37:29.954764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy.ext.declarative import declarative_base

# revision identifiers, used by Alembic.
revision = 'b6e81caa582f'
down_revision = 'c3b2faf138c0'
branch_labels = None
depends_on = None


Base = declarative_base()

# Define Event class for migration
class Event(Base):
    __tablename__ = 'event'
    __table_args__ = {'extend_existing': True} 

    id = sa.Column('id', sa.Integer(), primary_key=True)
    start_time = sa.Column('start_time', sa.BigInteger())
    end_time = sa.Column('end_time', sa.BigInteger())

# Define EventTime class for migration
class EventTime(Base):
    __tablename__ = 'event_time'
    __table_args__ = {'extend_existing': True} 

    id = sa.Column('id', sa.Integer(), nullable=False, primary_key=True)
    event_id = sa.Column('event_id', sa.Integer(), nullable=True)
    start_time = sa.Column('start_time', sa.BigInteger(), nullable=True)
    end_time = sa.Column('end_time', sa.BigInteger(), nullable=True)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('end_time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.commit()
    # Data Migration: Move the existing event times into the event_time table #
    events = session.query(Event)
    for event in events:
        session.add(
            EventTime(
                event_id=event.id,
                start_time=event.start_time,
                end_time=event.end_time
            )
        )
    session.commit()



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_time')
    # ### end Alembic commands ###
