"""Update event fields. Make start and end time long, add event_url, image_url, and event_emoji columns

Revision ID: bd3858beccdd
Revises: bfc9bdad220c
Create Date: 2020-07-27 19:47:28.329260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3858beccdd'
down_revision = 'bfc9bdad220c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_url', sa.String(length=256), nullable=True))
    op.add_column('event', sa.Column('image_url', sa.String(length=256), nullable=True))
    op.add_column('event', sa.Column('event_emoji', sa.String(length=64), nullable=True))
    op.alter_column('event', 'start_time', type_=sa.BigInteger())
    op.alter_column('event', 'end_time', type_=sa.BigInteger())
    op.alter_column('event', 'description', type_=sa.String(length=256))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'image_url')
    op.drop_column('event', 'event_url')
    op.drop_column('event', 'event_emoji')
    op.alter_column('event', 'start_time', type_=sa.Integer())
    op.alter_column('event', 'end_time', type_=sa.Integer())
    op.alter_column('event', 'description', type_=sa.String(length=64))
    # ### end Alembic commands ###