"""Add response time col for Event Response

Revision ID: c62f8f0dfe63
Revises: f13aba257d7c
Create Date: 2020-08-11 22:35:37.162924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62f8f0dfe63'
down_revision = 'f13aba257d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_response', sa.Column('response_time', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_response', 'response_time')
    # ### end Alembic commands ###
