"""Add image for squad

Revision ID: d2c4e7eeec1a
Revises: aabad5c84309
Create Date: 2020-09-09 22:25:19.004869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2c4e7eeec1a'
down_revision = 'aabad5c84309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squad', sa.Column('image', sa.Text(length=131072), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('squad', 'image')
    # ### end Alembic commands ###
