"""Increase char limit for various event fields

Revision ID: ff6fa6db6348
Revises: 32b24541db10
Create Date: 2020-08-15 15:57:53.893086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff6fa6db6348'
down_revision = '32b24541db10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'event_url',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=256),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('event', 'image_url',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=256),
               type_=sa.Text(length=65536),
               existing_nullable=True)
    op.alter_column('event', 'title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'title',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=64),
               existing_nullable=True)
    op.alter_column('event', 'image_url',
               existing_type=sa.Text(length=65536),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=256),
               existing_nullable=True)
    op.alter_column('event', 'event_url',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
